# Generated by Django 2.2.6 on 2021-08-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='posts.Post', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
